import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

const PRIMARY = [13, 110, 253];
const SUCCESS = [25, 135, 84];
const DARK = [33, 37, 41];
const LIGHT = [245, 247, 250];

const paymentName = {
  credit_card: "Credit Card",
  promptpay: "PromptPay",
  bank_transfer: "Bank Transfer",
  cod: "Cash on Delivery",
};

const formatMoney = (value) => `THB ${Number(value || 0).toLocaleString()}`;

const formatDate = () =>
  new Date().toLocaleString("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  });

async function captureElement(id) {
  const element = document.getElementById(id);

  if (!element) return null;

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
  });

  return canvas.toDataURL("image/png");
}

async function addResponsiveImage(pdf, imageData, x, y, width) {
  const img = new Image();
  img.src = imageData;

  await new Promise((resolve) => {
    img.onload = resolve;
  });

  const height = (img.height * width) / img.width;

  pdf.addImage(imageData, "PNG", x, y, width, height);

  return height;
}

function addFooter(pdf) {
  const pageCount = pdf.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);

    pdf.setDrawColor(220);

    pdf.line(15, 287, 195, 287);

    pdf.setFontSize(9);
    pdf.setTextColor(120);

    pdf.text("Generated by E-Commerce Admin System", 15, 292);

    pdf.text(`Page ${i} / ${pageCount}`, 195, 292, {
      align: "right",
    });
  }
}

const exportReportPDF = async ({
  summary,
  sales,
  products,
  paymentAnalytics,
  statusCards,
  salesGrowth,
}) => {
  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();

  

  // =============================
  // Cover Page
  // =============================

  pdf.setFillColor(...PRIMARY);

  pdf.rect(0, 0, pageWidth, 45, "F");

  pdf.setTextColor(255);

  pdf.setFontSize(28);

  pdf.setFont(undefined, "bold");

  pdf.text("E-Commerce", pageWidth / 2, 22, {
    align: "center",
  });

  pdf.setFontSize(20);

  pdf.text("Sales Report", pageWidth / 2, 35, {
    align: "center",
  });

  pdf.setTextColor(...DARK);

  pdf.setFontSize(18);

  pdf.text("Business Performance Report", pageWidth / 2, 70, {
    align: "center",
  });

  pdf.setDrawColor(...PRIMARY);

  pdf.line(40, 80, 170, 80);

  pdf.setFontSize(12);

  pdf.setFont(undefined, "normal");

  pdf.text(`Generated : ${formatDate()}`, 30, 105);

  pdf.text("Prepared By : Administrator", 30, 115);

  pdf.text("System : E-Commerce Admin", 30, 125);

  pdf.setFillColor(...LIGHT);

  pdf.roundedRect(25, 145, 160, 60, 4, 4, "F");

  pdf.setFont(undefined, "bold");

  pdf.setFontSize(15);

  pdf.text("Report Overview", 35, 160);

  pdf.setFont(undefined, "normal");

  pdf.setFontSize(11);

  pdf.text(
    [
      "This report contains sales analytics, revenue summary,",
      "order performance, payment statistics and",
      "top selling products generated from",
      "the E-Commerce Management System.",
    ],
    35,
    172,
  );

  pdf.setTextColor(120);

  pdf.setFontSize(10);

  pdf.text("Confidential Business Report", pageWidth / 2, 260, {
    align: "center",
  });

  pdf.addPage();

  // ========
  // Part 2
  // ========
  // KPI Summary
  // Revenue Chart
  // จะทำต่อใน Part 2

  // =============================
  // Dashboard Summary
  // =============================

  pdf.setFontSize(20);
  pdf.setTextColor(...DARK);
  pdf.setFont(undefined, "bold");
  pdf.text("Dashboard Summary", 15, 20);

  let startY = 35;

  const cardWidth = 82;
  const cardHeight = 28;

  const drawCard = (x, y, title, value, color = PRIMARY) => {
    pdf.setFillColor(248, 249, 250);
    pdf.roundedRect(x, y, cardWidth, cardHeight, 3, 3, "F");

    pdf.setDrawColor(...color);
    pdf.roundedRect(x, y, cardWidth, cardHeight, 3, 3);

    pdf.setFontSize(10);
    pdf.setTextColor(120);
    pdf.setFont(undefined, "normal");
    pdf.text(title, x + 6, y + 8);

    pdf.setFontSize(18);
    pdf.setFont(undefined, "bold");
    pdf.setTextColor(...DARK);
    pdf.text(value, x + 6, y + 20);
  };

  drawCard(15, startY, "Total Revenue", formatMoney(summary.total_revenue));

  drawCard(110, startY, "Total Orders", String(summary.total_orders));

  drawCard(
    15,
    startY + 36,
    "Average Order",
    formatMoney(summary.average_order_value),
  );

  drawCard(
    110,
    startY + 36,
    "Sales Growth",
    `${salesGrowth > 0 ? "+" : ""}${salesGrowth}%`,
    SUCCESS,
  );

  startY += 88;

  // =============================
  // Revenue Trend
  // =============================

  pdf.setFontSize(16);
  pdf.setTextColor(...DARK);
  

  const revenueImage = await captureElement("revenue-chart");

  if (revenueImage) {
    const height = await addResponsiveImage(pdf, revenueImage, 15, startY, 180);

    startY += height + 10;
  } else {
    pdf.setFontSize(11);

    pdf.setTextColor(150);

    pdf.text("Revenue chart unavailable.", 15, startY + 15);

    startY += 20;
  }

  // =============================
  // Order Analytics
  // =============================

  pdf.setFontSize(16);
  pdf.setTextColor(...DARK);

  

  const orderImage = await captureElement("order-analytics");

 if (orderImage) {
  await addResponsiveImage(
    pdf,
    orderImage,
    15,
    startY,
    180
  );



  
  } else {
    autoTable(pdf, {
      startY: startY + 5,

      head: [["Status", "Orders"]],

      body: statusCards.map((item) => [item.label, item.value]),

      headStyles: {
        fillColor: PRIMARY,
      },

      styles: {
        fontSize: 10,
      },
    });

  }

  pdf.addPage();

  // =============================
  // Part 3
  // =============================

  // =============================
  // Top Selling Products
  // =============================

  pdf.setFontSize(20);
  pdf.setTextColor(...DARK);
  pdf.setFont(undefined, "bold");
  pdf.text("Top Selling Products", 15, 20);

  autoTable(pdf, {
    startY: 28,

    head: [["Product", "Quantity Sold", "Revenue"]],

    body: products.map((item) => [
      item.product_name,
      item.quantity_sold,
      formatMoney(item.revenue),
    ]),

    headStyles: {
      fillColor: PRIMARY,
      textColor: 255,
      halign: "center",
    },

    bodyStyles: {
      fontSize: 10,
    },

    alternateRowStyles: {
      fillColor: [248, 249, 250],
    },

    styles: {
      cellPadding: 4,
      valign: "middle",
    },
  });

  let y = pdf.lastAutoTable.finalY + 15;

  // =============================
  // Payment Analytics
  // =============================

  pdf.setFontSize(18);
  pdf.setTextColor(...DARK);
 

  const paymentImage = await captureElement("payment-analytics");

  if (paymentImage) {
    const height = await addResponsiveImage(pdf, paymentImage, 15, y, 180);

    y += height + 10;

   
  } else {
    autoTable(pdf, {
      startY: y + 5,

      head: [["Payment Method", "Transactions", "Percentage"]],

      body: paymentAnalytics.map((item) => [
        paymentName[item.method] || item.method,
        item.count,
        `${item.percentage}%`,
      ]),

      headStyles: {
        fillColor: SUCCESS,
      },

      alternateRowStyles: {
        fillColor: [248, 249, 250],
      },
    });

    y = pdf.lastAutoTable.finalY + 15;
  }

  // =============================
  // Monthly Revenue Summary
  // =============================


  if (y > 220) {
    pdf.addPage();
    y = 20;
  }

  pdf.setFontSize(18);
  pdf.setTextColor(...DARK);

  pdf.text("Monthly Revenue Summary", 15, y);

  autoTable(pdf, {
    startY: y + 5,

    head: [["Month", "Revenue", "Orders"]],

    body: sales.map((item) => [
      item.month,

      formatMoney(item.revenue),

      item.order_count,
    ]),

    headStyles: {
      fillColor: PRIMARY,

      textColor: 255,
    },

    alternateRowStyles: {
      fillColor: [248, 249, 250],
    },

    styles: {
      cellPadding: 4,

      fontSize: 10,
    },
  });

  pdf.addPage();

  // =============================
  // Part 4
  // =============================

    // =============================
  // Executive Summary
  // =============================

  pdf.setFontSize(20);
  pdf.setFont(undefined, "bold");
  pdf.setTextColor(...DARK);

  pdf.text("Executive Summary", 15, 20);

  pdf.setDrawColor(...PRIMARY);
  pdf.line(15, 24, 85, 24);

  pdf.setFont(undefined, "normal");
  pdf.setFontSize(13);

  const summaryText = [
    `• Total Revenue : ${formatMoney(summary.total_revenue)}`,

    `• Total Orders : ${summary.total_orders}`,

    `• Average Order Value : ${formatMoney(summary.average_order_value)}`,

    `• Sales Growth : ${salesGrowth > 0 ? "+" : ""}${salesGrowth}%`,

    `• Top Products Listed : ${products.length}`,

    `• Payment Methods : ${paymentAnalytics.length}`,

    "",

    "This report was automatically generated",

    "from the E-Commerce Management System.",

    "The information presented reflects",

    "business performance based on current",

    "database records.",
  ];

  pdf.text(summaryText, 20, 42);

  // =============================
  // Highlight Box
  // =============================

  pdf.setFillColor(248,249,250);

  pdf.roundedRect(

    15,

    110,

    180,

    45,

    3,

    3,

    "F"

  );

  pdf.setFont(undefined,"bold");

  pdf.setFontSize(14);

  pdf.text(

    "Report Generated Successfully",

    22,

    125

  );

  pdf.setFont(undefined,"normal");

  pdf.setFontSize(11);

  pdf.text(

    [

      "This document contains dashboard analytics,",

      "sales summary, payment statistics,",

      "monthly revenue and top selling products.",

    ],

    22,

    136

  );

  // =============================
  // Thank You
  // =============================

  pdf.setFontSize(22);

  pdf.setTextColor(...PRIMARY);

  pdf.setFont(undefined,"bold");

  pdf.text(
    "Report Completed",

    105,

    215,

    {
      align: "center",
    },
  );

  pdf.setFontSize(11);

  pdf.setTextColor(120);

  pdf.setFont(undefined,"normal");

  pdf.text(

    "Generated by E-Commerce Admin System",

    105,

    225,

    {

      align:"center"

    }

  );

  // =============================
  // Footer
  // =============================

  addFooter(pdf);

  // =============================
  // Download
  // =============================


pdf.setProperties({
  title: "Sales Report",
  subject: "Business Report",
  author: "E-Commerce Admin",
  creator: "E-Commerce System",
});

  pdf.save(

    `Sales_Report_${Date.now()}.pdf`

  );

};


export default exportReportPDF;
